name: Link check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lychee:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress .
